#!/bin/bash
rm -f test_mGPU

arch=CC30 #CC35
mrch=sm_30 #sm_35

enable_double=""
if [ -n "$1" ]
then
  if (("$1" == "double"))
  then
    arch=CC30
    mrch=sm_30
    enable_double="-DUSEDOUBLE"
  fi
fi

MYTOOLS="/home/dan/tools"
INC="-I/usr/local/cuda-9.0/include -I/usr/local/cuda-9.0/samples/common/inc -I${MYTOOLS}/include -I${MYTOOLS}/include/mesh1" #-I${MYTOOLS}/nvml/include 
cuLIB="/usr/local/cuda-9.0/lib64"
LIB="-L${cuLIB} -L${MYTOOLS}/lib" #-L${MYTOOLS}/nvml/lib64"
fm= #--use_fast_math #coment it if you whant divisions and transcend funcs to be IEEE or something similar to IEEE
gccOPTS="-fPIC -std=c++11 -O3"
echo "cleaning..."
rm -f *.obj appl

echo "compiling..."
echo "   gpu..."
echo "simple.cu"
/usr/local/cuda-9.0/bin/nvcc -w -Xcompiler -fPIC ${enable_double} $INC -O3 -c -arch=$mrch $fm src/simple.cu -o simple.obj
echo "simple.cu -DSTATIC static means no moving window"

/usr/local/cuda-9.0/bin/nvcc -w -Xcompiler -fPIC -DSTATIC ${enable_double} $INC -O3 -c -arch=$mrch $fm src/simple.cu -o simple_static.obj

echo "service.cu"
/usr/local/cuda-9.0/bin/nvcc -w -Xcompiler -fPIC ${enable_double} $INC -O3 -c -arch=$mrch $fm src/service.cu -o service.obj

echo "   cpu..."
echo "   geo.cpp"
/usr/bin/g++-6 -g $INC ${gccOPTS} ${enable_double} -Wall -Werror src/geo.cpp -c -o geo.obj
echo "   test.cpp"
/usr/bin/g++-6 -g $INC ${gccOPTS} ${enable_double} -Wall -Werror src/test.cpp -c -fopenmp -o test.obj

MYLIBS="-lsimpledraw_glfw3 -lzstream -lsvg1 -lmesh1 -ltclient -lgetGPUtemp" #-lnvidia-ml
#MYLIBS="-lsimpledraw_glfw3 -lzstream -lsvg1 -lmesh1 -lgetGPUtemp" #-lgetGPUtemp #-lnvidia-ml

echo "linking..."
/usr/bin/g++-6 -fPIC $LIB geo.obj test.obj simple.obj service.obj ${MYLIBS} -Wl,-rpath=${MYTOOLS}/lib -Wl,-rpath=${cuLIB} -fopenmp -lpthread -lcudart -o test_mGPU

echo "linking static..."
/usr/bin/g++-6 -g -fPIC $LIB geo.obj test.obj simple_static.obj service.obj ${MYLIBS} -Wl,-rpath=${MYTOOLS}/lib -Wl,-rpath=${cuLIB} -fopenmp -lpthread -lcudart -o test_mGPU_static

echo "compiling python wrappers"
/usr/bin/g++-6 ${INC} ${gccOPTS} -g src/pyAPI.cpp -c -o pyAPI.o -DPYMODNAME=pyEmpMe -I/usr/include/python3.9

/usr/bin/g++-6 ${INC} ${gccOPTS} src/pyAPI.cpp -c -o pyAPI_static.o -DSTATIC -DPYMODNAME=pyEmpMe_static -I/usr/include/python3.9

echo "linking python library"
/usr/bin/g++-6 $LIB -fPIC pyAPI_static.o geo.obj simple_static.obj service.obj ${MYLIBS} -Wl,-rpath=${MYTOOLS}/lib -Wl,-rpath=${cuLIB} -fopenmp -lpthread -lcudart -o pyEmpMe_static.so -shared

/usr/bin/g++-6 $LIB -fPIC pyAPI.o geo.obj simple.obj service.obj ${MYLIBS} -Wl,-rpath=${MYTOOLS}/lib -Wl,-rpath=${cuLIB} -fopenmp -lpthread -lcudart -o pyEmpMe.so -shared

rm -f *.obj
